### ISSUE TITLE
Example walkthrough and Task Manifest

### ISSUE THREAD

**Issue by mjbrender** [intelsdi-x/snap-plugin-publisher-rabbitmq#22]
Please add a walkthrough example of how to use this plugin. Specifically:

Task Manifest using of the plugin under examples/ folder
Workflow of using the the task with a collector plugin of your choice
Preferably, have a Dockerfile or refer to a Dockerfile of etcd that can be used as an example.

See:

https://github.com/intelsdi-x/snap-plugin-collector-cassandra/tree/master/examples/tasks
https://github.com/intelsdi-x/snap-plugin-collector-cassandra#examples

**Comment by katarzyna-z** [comment]
Exemplary [task manifest](https://github.com/intelsdi-x/snap-plugin-publisher-rabbitmq/blob/master/examples/tasks/psutil-rabbitmq.json) was added, [exemples section](https://github.com/intelsdi-x/snap-plugin-publisher-rabbitmq#examples) also was added so I'm closing this issue.

**Comment by mjbrender** [comment]
Thanks @katarzyna-z!
